spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:payments
    username: sa
    password:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true